# Generated by Django 4.2.1 on 2023-05-24 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='sorteios')),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_premio', models.IntegerField()),
                ('descricao_premio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promocaos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_cotas', models.IntegerField()),
                ('preco_cotas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.FloatField()),
                ('qtd_bilhetes', models.IntegerField()),
                ('data_sorteio', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('images_sorteio', models.ManyToManyField(to='sorteio.images_sorteio')),
                ('premios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteio.premios')),
                ('promocaos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteio.promocaos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
