# Generated by Django 4.2.1 on 2023-05-25 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteio',
            name='images_sorteio',
            field=models.ManyToManyField(blank=True, to='sorteio.images_sorteio'),
        ),
        migrations.AlterField(
            model_name='sorteio',
            name='premios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sorteio.premios'),
        ),
        migrations.AlterField(
            model_name='sorteio',
            name='promocaos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sorteio.promocaos'),
        ),
    ]
