# Generated by Django 4.2.1 on 2023-05-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0002_alter_sorteio_images_sorteio_alter_sorteio_premios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteio',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
