# Generated by Django 4.1.1 on 2023-05-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0004_remove_sorteio_premios_remove_sorteio_promocaos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteio',
            name='images_sorteio',
        ),
        migrations.DeleteModel(
            name='Images_sorteio',
        ),
    ]
