# Generated by Django 4.1.1 on 2023-05-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0007_remove_premios_sorteio_sorteio_premio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteio',
            name='premio',
        ),
        migrations.AddField(
            model_name='sorteio',
            name='premio',
            field=models.ManyToManyField(related_name='sorteios', to='sorteio.premios'),
        ),
    ]
